### ISSUE TITLE
Multivariate Case

### ISSUE THREAD

**Issue by rob-med** [isakkarlsson/wildboar#6]
Hi! 
Thanks a lot for providing the code alongside the paper!
I managed to get the examples running but all the datasets are univariate, if I'm not mistaken.

I am wondering what's the format expected for a multivariate dataset?
Could you provide a (minimal) working example?

**Comment by isakkarlsson** [comment]
Hi!

Thanks. Sorry about the poor documentation.

For multivariate datasets the shape of the input array is expected as: `[n_samples, n_dimensions, n_timesteps]`, reshaped as `[n_samples, -1]`, with the parameter `force_dim` set to `n_dimensions`.

I will provide a working example, and fix #5 to improve the usability of the code.

Cheers,
Isak
