### ISSUE TITLE
will it work for  multivariate  time series classification for example mixture of categorical and continues data? 

### ISSUE THREAD

**Issue by Sandy4321** [isakkarlsson/wildboar#9]
**Is your feature request related to a problem? Please describe.**

	will it work for  multivariate  time series classification for example mixture of categorical and continues data? 
	for example at time t1 we have observation: red, 2.4 , 5, 12.456 and time t2: green, 3.5, 2, 45.78; time t3: black, 5.6, 7, 23.56; t4: red, 2.1, 5, 12.6 ?

**Comment by isakkarlsson** [comment]
Hi!

It will "work" assuming the categories are converted to real-values and the euclidean distance make sense for those values.

As of yet, the library does not yet support different distance measures per channel of a multivariate time series.

I'll mark this as a feature request and close it.

Regards,
Isak
